[governance]
communityMultisig = "0xFEA47018D632A77bA579846c840d5706705Dc598"
executorMultisig = "0x369e6F597e22EaB55fFb173C6d9cD234BD699111"
operationsMultisig = "0xBE1685C81aA44FF9FB319dD389addd9374383e90"
pauserMultisig = "0x5050389572f2d220ad927CcbeA0D406831012390"
timelock = "0xA6Db1A8C5a981d1536266D2a393c5F8dDb210EAF"

[protocol]
allocationManager = "0x0000000000000000000000000000000000000000"
avsDirectory = "0x135dda560e946695d6f155dacafc6f1f25c1f5af"
# beaconOracle = "0x343907185b71aDF0eBa9567538314396aa985442"
beigen = "0x83E9115d334D248Ce39a6f36144aEaB5b3456e75"
delayedWithdrawalRouter = "0x7Fe7E9CC0F274d2435AD5d56D5fa73E47F6A23D8"
delegationManager = "0x39053D51B77DC0d36036Fc1fCc8Cb819df8Ef37A"
eigen = "0xec53bf9167f50cdeb3ae105f56099aaab9061f83"
eigenLayerPauserReg = "0x0c431C66F4dE941d089625E5B423D00707977060"
eigenLayerProxyAdmin = "0x8b9566AdA63B64d1E1dcF1418b43fd1433b72444"
eigenPodBeacon = "0x5a2a4F2F3C18f09179B6703e63D9eDD165909073"
eigenPodManager = "0x91E677b07F7AF907ec9a428aafA9fc14a0d3A338"
eigenStrategy = "0xaCB55C530Acdb2849e6d4f36992Cd8c9D50ED8F7"
permissionController = "0x0000000000000000000000000000000000000000"
rewardsCoordinator = "0x7750d328b314EfFa365A0402CcfD489B80B0adda"
strategyFactory = "0x5e4C39Ad7A3E881585e383dB9827EB4811f6F647"
strategyFactoryBeacon = "0x0ed6703C298d28aE0878d1b28e88cA87F9662fE9"
strategyManager = "0x858646372CC42E1A627fcE94aa7A7033e7CF075A"

[strategies]
addresses = [
    "0x93c4b944D05dfe6df7645A86cd2206016c51564D", # stETH
    "0x1BeE69b7dFFfA4E2d53C2a2Df135C388AD25dCD2", # rETH
    "0x54945180dB7943c0ed0FEE7EdaB2Bd24620256bc", # cbETH
    "0x9d7eD45EE2E8FC5482fa2428f15C971e6369011d", # ETHx
    "0x13760F50a9d7377e4F20CB8CF9e4c26586c658ff", # ankrETH
    "0xa4C637e0F704745D182e4D38cAb7E7485321d059", # oETH
    "0x57ba429517c3473B6d34CA9aCd56c0e735b94c02", # osETH
    "0x0Fe4F44beE93503346A3Ac9EE5A26b130a5796d6", # swETH
    "0x7CA911E83dabf90C90dD3De5411a10F1A6112184", # wBETH
    "0x8CA7A5d6f3acd3A7A8bC468a8CD0FB14B6BD28b6", # sfrxETH
    "0xAe60d8180437b5C34bB956822ac2710972584473", # lsETH
    "0x298aFB19A105D59E74658C4C334Ff360BadE6dd2"  # mETH
]